spring.application.name=kolog-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

jwt.secret=${JWT_SECRET}

# 파일을 실제로 저장할 하드디스크 경로
file.upload-dir=/Users/yangjeong-woo/Documents/kolog_storage/
# 외부에서 접근할 때 사용할 서버 주소 (로컬 테스트용)
file.server-url=http://localhost:8080

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB